// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/paraU/control/control.proto

package control

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ControlMessage_DostStatusUpdateStatus int32

const (
	ControlMessage_DostStatusUpdate_approved ControlMessage_DostStatusUpdateStatus = 0
	ControlMessage_DostStatusUpdate_rejected ControlMessage_DostStatusUpdateStatus = 1
)

var ControlMessage_DostStatusUpdateStatus_name = map[int32]string{
	0: "approved",
	1: "rejected",
}

var ControlMessage_DostStatusUpdateStatus_value = map[string]int32{
	"approved": 0,
	"rejected": 1,
}

func (x ControlMessage_DostStatusUpdateStatus) String() string {
	return proto.EnumName(ControlMessage_DostStatusUpdateStatus_name, int32(x))
}

func (ControlMessage_DostStatusUpdateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_742c5f21fbd90dad, []int{0, 1, 0}
}

type ControlMessage struct {
	// Types that are valid to be assigned to Msg:
	//	*ControlMessage_Introduction_
	//	*ControlMessage_DostStatusUpdate_
	Msg                  isControlMessage_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ControlMessage) Reset()         { *m = ControlMessage{} }
func (m *ControlMessage) String() string { return proto.CompactTextString(m) }
func (*ControlMessage) ProtoMessage()    {}
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_742c5f21fbd90dad, []int{0}
}

func (m *ControlMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlMessage.Unmarshal(m, b)
}
func (m *ControlMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlMessage.Marshal(b, m, deterministic)
}
func (m *ControlMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlMessage.Merge(m, src)
}
func (m *ControlMessage) XXX_Size() int {
	return xxx_messageInfo_ControlMessage.Size(m)
}
func (m *ControlMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ControlMessage proto.InternalMessageInfo

type isControlMessage_Msg interface {
	isControlMessage_Msg()
}

type ControlMessage_Introduction_ struct {
	Introduction *ControlMessage_Introduction `protobuf:"bytes,1,opt,name=introduction,proto3,oneof"`
}

type ControlMessage_DostStatusUpdate_ struct {
	DostStatusUpdate *ControlMessage_DostStatusUpdate `protobuf:"bytes,2,opt,name=dost_status_update,json=dostStatusUpdate,proto3,oneof"`
}

func (*ControlMessage_Introduction_) isControlMessage_Msg() {}

func (*ControlMessage_DostStatusUpdate_) isControlMessage_Msg() {}

func (m *ControlMessage) GetMsg() isControlMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ControlMessage) GetIntroduction() *ControlMessage_Introduction {
	if x, ok := m.GetMsg().(*ControlMessage_Introduction_); ok {
		return x.Introduction
	}
	return nil
}

func (m *ControlMessage) GetDostStatusUpdate() *ControlMessage_DostStatusUpdate {
	if x, ok := m.GetMsg().(*ControlMessage_DostStatusUpdate_); ok {
		return x.DostStatusUpdate
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ControlMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ControlMessage_Introduction_)(nil),
		(*ControlMessage_DostStatusUpdate_)(nil),
	}
}

type ControlMessage_Introduction struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlMessage_Introduction) Reset()         { *m = ControlMessage_Introduction{} }
func (m *ControlMessage_Introduction) String() string { return proto.CompactTextString(m) }
func (*ControlMessage_Introduction) ProtoMessage()    {}
func (*ControlMessage_Introduction) Descriptor() ([]byte, []int) {
	return fileDescriptor_742c5f21fbd90dad, []int{0, 0}
}

func (m *ControlMessage_Introduction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlMessage_Introduction.Unmarshal(m, b)
}
func (m *ControlMessage_Introduction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlMessage_Introduction.Marshal(b, m, deterministic)
}
func (m *ControlMessage_Introduction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlMessage_Introduction.Merge(m, src)
}
func (m *ControlMessage_Introduction) XXX_Size() int {
	return xxx_messageInfo_ControlMessage_Introduction.Size(m)
}
func (m *ControlMessage_Introduction) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlMessage_Introduction.DiscardUnknown(m)
}

var xxx_messageInfo_ControlMessage_Introduction proto.InternalMessageInfo

func (m *ControlMessage_Introduction) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *ControlMessage_Introduction) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type ControlMessage_DostStatusUpdate struct {
	FromPeerId           string                                `protobuf:"bytes,1,opt,name=from_peer_id,json=fromPeerId,proto3" json:"from_peer_id,omitempty"`
	ToPeerId             string                                `protobuf:"bytes,2,opt,name=to_peer_id,json=toPeerId,proto3" json:"to_peer_id,omitempty"`
	UpdatedStatus        ControlMessage_DostStatusUpdateStatus `protobuf:"varint,3,opt,name=updated_status,json=updatedStatus,proto3,enum=control.ControlMessage_DostStatusUpdateStatus" json:"updated_status,omitempty"`
	Meta                 *ControlMessage_DostStatusUpdate_Meta `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ControlMessage_DostStatusUpdate) Reset()         { *m = ControlMessage_DostStatusUpdate{} }
func (m *ControlMessage_DostStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*ControlMessage_DostStatusUpdate) ProtoMessage()    {}
func (*ControlMessage_DostStatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_742c5f21fbd90dad, []int{0, 1}
}

func (m *ControlMessage_DostStatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlMessage_DostStatusUpdate.Unmarshal(m, b)
}
func (m *ControlMessage_DostStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlMessage_DostStatusUpdate.Marshal(b, m, deterministic)
}
func (m *ControlMessage_DostStatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlMessage_DostStatusUpdate.Merge(m, src)
}
func (m *ControlMessage_DostStatusUpdate) XXX_Size() int {
	return xxx_messageInfo_ControlMessage_DostStatusUpdate.Size(m)
}
func (m *ControlMessage_DostStatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlMessage_DostStatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ControlMessage_DostStatusUpdate proto.InternalMessageInfo

func (m *ControlMessage_DostStatusUpdate) GetFromPeerId() string {
	if m != nil {
		return m.FromPeerId
	}
	return ""
}

func (m *ControlMessage_DostStatusUpdate) GetToPeerId() string {
	if m != nil {
		return m.ToPeerId
	}
	return ""
}

func (m *ControlMessage_DostStatusUpdate) GetUpdatedStatus() ControlMessage_DostStatusUpdateStatus {
	if m != nil {
		return m.UpdatedStatus
	}
	return ControlMessage_DostStatusUpdate_approved
}

func (m *ControlMessage_DostStatusUpdate) GetMeta() *ControlMessage_DostStatusUpdate_Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ControlMessage_DostStatusUpdate_Meta struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlMessage_DostStatusUpdate_Meta) Reset()         { *m = ControlMessage_DostStatusUpdate_Meta{} }
func (m *ControlMessage_DostStatusUpdate_Meta) String() string { return proto.CompactTextString(m) }
func (*ControlMessage_DostStatusUpdate_Meta) ProtoMessage()    {}
func (*ControlMessage_DostStatusUpdate_Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_742c5f21fbd90dad, []int{0, 1, 0}
}

func (m *ControlMessage_DostStatusUpdate_Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlMessage_DostStatusUpdate_Meta.Unmarshal(m, b)
}
func (m *ControlMessage_DostStatusUpdate_Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlMessage_DostStatusUpdate_Meta.Marshal(b, m, deterministic)
}
func (m *ControlMessage_DostStatusUpdate_Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlMessage_DostStatusUpdate_Meta.Merge(m, src)
}
func (m *ControlMessage_DostStatusUpdate_Meta) XXX_Size() int {
	return xxx_messageInfo_ControlMessage_DostStatusUpdate_Meta.Size(m)
}
func (m *ControlMessage_DostStatusUpdate_Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlMessage_DostStatusUpdate_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_ControlMessage_DostStatusUpdate_Meta proto.InternalMessageInfo

func (m *ControlMessage_DostStatusUpdate_Meta) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterEnum("control.ControlMessage_DostStatusUpdateStatus", ControlMessage_DostStatusUpdateStatus_name, ControlMessage_DostStatusUpdateStatus_value)
	proto.RegisterType((*ControlMessage)(nil), "control.ControlMessage")
	proto.RegisterType((*ControlMessage_Introduction)(nil), "control.ControlMessage.Introduction")
	proto.RegisterType((*ControlMessage_DostStatusUpdate)(nil), "control.ControlMessage.DostStatusUpdate")
	proto.RegisterType((*ControlMessage_DostStatusUpdate_Meta)(nil), "control.ControlMessage.DostStatusUpdate.Meta")
}

func init() {
	proto.RegisterFile("pkg/paraU/control/control.proto", fileDescriptor_742c5f21fbd90dad)
}

var fileDescriptor_742c5f21fbd90dad = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4f, 0xf2, 0x40,
	0x10, 0xc7, 0x29, 0xf4, 0xe1, 0x65, 0x9e, 0x3e, 0xa4, 0xd9, 0xcb, 0xd3, 0xa0, 0x89, 0x04, 0x39,
	0x70, 0xb1, 0x24, 0xf8, 0x09, 0x54, 0x0e, 0x60, 0x82, 0x31, 0x35, 0x18, 0x6f, 0xcd, 0xca, 0x8e,
	0x04, 0xb5, 0xec, 0x66, 0x77, 0xea, 0x67, 0xf3, 0xe4, 0x67, 0x33, 0xdd, 0x2d, 0x86, 0x92, 0x98,
	0x70, 0x6a, 0xe7, 0x3f, 0xf3, 0xff, 0xcd, 0x4b, 0x16, 0xce, 0xd4, 0xdb, 0x7a, 0xac, 0xb8, 0xe6,
	0xcb, 0xf1, 0x4a, 0x6e, 0x49, 0xcb, 0xf7, 0xdd, 0x37, 0x56, 0x5a, 0x92, 0x64, 0xad, 0x32, 0x1c,
	0x7c, 0xf9, 0xd0, 0xbd, 0x71, 0xff, 0x0b, 0x34, 0x86, 0xaf, 0x91, 0xdd, 0x42, 0xb0, 0x29, 0x04,
	0x91, 0xaf, 0x68, 0x23, 0xb7, 0x91, 0xd7, 0xf7, 0x46, 0x7f, 0x27, 0xc3, 0x78, 0x47, 0xa8, 0x96,
	0xc7, 0xf3, 0xbd, 0xda, 0x59, 0x2d, 0xa9, 0x78, 0xd9, 0x13, 0x30, 0x21, 0x0d, 0xa5, 0x86, 0x38,
	0xe5, 0x26, 0xcd, 0x95, 0xe0, 0x84, 0x51, 0xdd, 0x12, 0x47, 0xbf, 0x11, 0xa7, 0xd2, 0xd0, 0x83,
	0x35, 0x2c, 0x6d, 0xfd, 0xac, 0x96, 0x84, 0xe2, 0x40, 0xeb, 0x4d, 0x21, 0xd8, 0xef, 0xcc, 0xfe,
	0x43, 0x4b, 0x21, 0xea, 0x74, 0x23, 0xec, 0xc0, 0x9d, 0xa4, 0x59, 0x84, 0x73, 0xc1, 0x4e, 0xa0,
	0x93, 0x1b, 0xd4, 0xe9, 0x96, 0x67, 0xae, 0x73, 0x27, 0x69, 0x17, 0xc2, 0x1d, 0xcf, 0xb0, 0xf7,
	0x59, 0x87, 0xf0, 0xb0, 0x1d, 0xeb, 0x43, 0xf0, 0xa2, 0x65, 0x96, 0x56, 0x79, 0x50, 0x68, 0xf7,
	0x8e, 0x79, 0x0a, 0x40, 0xf2, 0x27, 0x5f, 0x42, 0x49, 0x96, 0xd9, 0x47, 0xe8, 0xba, 0x45, 0x45,
	0xb9, 0x77, 0xd4, 0xe8, 0x7b, 0xa3, 0xee, 0x64, 0x7c, 0xec, 0xc2, 0xb1, 0xb3, 0x25, 0xff, 0x4a,
	0x8c, 0xcb, 0xb1, 0x2b, 0xf0, 0x33, 0x24, 0x1e, 0xf9, 0xf6, 0x7c, 0x17, 0x47, 0xd3, 0x16, 0x48,
	0x3c, 0xb1, 0xd6, 0xde, 0x39, 0xf8, 0x45, 0x54, 0x3d, 0x8a, 0x57, 0x3d, 0xca, 0x60, 0x08, 0x4d,
	0x37, 0x00, 0x0b, 0xa0, 0xcd, 0x95, 0xd2, 0xf2, 0x03, 0x45, 0x58, 0x2b, 0x22, 0x8d, 0xaf, 0xb8,
	0x22, 0x14, 0xa1, 0x77, 0xfd, 0x07, 0x1a, 0x99, 0x59, 0x3f, 0x37, 0xed, 0x83, 0xba, 0xfc, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x1c, 0x91, 0x4b, 0x18, 0x73, 0x02, 0x00, 0x00,
}
