// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/paraU/chat/chat.proto

package chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatMessage struct {
	Meta *ChatMessage_Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are valid to be assigned to Msg:
	//	*ChatMessage_Text_
	Msg                  isChatMessage_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aece4bc8939359f, []int{0}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetMeta() *ChatMessage_Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type isChatMessage_Msg interface {
	isChatMessage_Msg()
}

type ChatMessage_Text_ struct {
	Text *ChatMessage_Text `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

func (*ChatMessage_Text_) isChatMessage_Msg() {}

func (m *ChatMessage) GetMsg() isChatMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ChatMessage) GetText() *ChatMessage_Text {
	if x, ok := m.GetMsg().(*ChatMessage_Text_); ok {
		return x.Text
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ChatMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ChatMessage_Text_)(nil),
	}
}

type ChatMessage_Meta struct {
	FromPeer             string   `protobuf:"bytes,1,opt,name=from_peer,json=fromPeer,proto3" json:"from_peer,omitempty"`
	ToPeer               string   `protobuf:"bytes,2,opt,name=to_peer,json=toPeer,proto3" json:"to_peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage_Meta) Reset()         { *m = ChatMessage_Meta{} }
func (m *ChatMessage_Meta) String() string { return proto.CompactTextString(m) }
func (*ChatMessage_Meta) ProtoMessage()    {}
func (*ChatMessage_Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aece4bc8939359f, []int{0, 0}
}

func (m *ChatMessage_Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage_Meta.Unmarshal(m, b)
}
func (m *ChatMessage_Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage_Meta.Marshal(b, m, deterministic)
}
func (m *ChatMessage_Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage_Meta.Merge(m, src)
}
func (m *ChatMessage_Meta) XXX_Size() int {
	return xxx_messageInfo_ChatMessage_Meta.Size(m)
}
func (m *ChatMessage_Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage_Meta proto.InternalMessageInfo

func (m *ChatMessage_Meta) GetFromPeer() string {
	if m != nil {
		return m.FromPeer
	}
	return ""
}

func (m *ChatMessage_Meta) GetToPeer() string {
	if m != nil {
		return m.ToPeer
	}
	return ""
}

type ChatMessage_Text struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage_Text) Reset()         { *m = ChatMessage_Text{} }
func (m *ChatMessage_Text) String() string { return proto.CompactTextString(m) }
func (*ChatMessage_Text) ProtoMessage()    {}
func (*ChatMessage_Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aece4bc8939359f, []int{0, 1}
}

func (m *ChatMessage_Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage_Text.Unmarshal(m, b)
}
func (m *ChatMessage_Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage_Text.Marshal(b, m, deterministic)
}
func (m *ChatMessage_Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage_Text.Merge(m, src)
}
func (m *ChatMessage_Text) XXX_Size() int {
	return xxx_messageInfo_ChatMessage_Text.Size(m)
}
func (m *ChatMessage_Text) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage_Text.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage_Text proto.InternalMessageInfo

func (m *ChatMessage_Text) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "chat.ChatMessage")
	proto.RegisterType((*ChatMessage_Meta)(nil), "chat.ChatMessage.Meta")
	proto.RegisterType((*ChatMessage_Text)(nil), "chat.ChatMessage.Text")
}

func init() {
	proto.RegisterFile("pkg/paraU/chat/chat.proto", fileDescriptor_7aece4bc8939359f)
}

var fileDescriptor_7aece4bc8939359f = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0xc8, 0x4e, 0xd7,
	0x2f, 0x48, 0x2c, 0x4a, 0x0c, 0xd5, 0x4f, 0xce, 0x48, 0x2c, 0x01, 0x13, 0x7a, 0x05, 0x45, 0xf9,
	0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0xd2, 0x09, 0x46, 0x2e, 0x6e, 0xe7, 0x8c, 0xc4, 0x12, 0xdf,
	0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x21, 0x2d, 0x2e, 0x96, 0xdc, 0xd4, 0x92, 0x44, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0x6e, 0x23, 0x31, 0x3d, 0xb0, 0x06, 0x24, 0x05, 0x7a, 0xbe, 0xa9, 0x25, 0x89,
	0x41, 0x60, 0x35, 0x42, 0x3a, 0x5c, 0x2c, 0x25, 0xa9, 0x15, 0x25, 0x12, 0x4c, 0xb8, 0xd4, 0x86,
	0xa4, 0x56, 0x94, 0x78, 0x30, 0x04, 0x81, 0x55, 0x49, 0xd9, 0x70, 0xb1, 0x80, 0xf4, 0x0a, 0x49,
	0x73, 0x71, 0xa6, 0x15, 0xe5, 0xe7, 0xc6, 0x17, 0xa4, 0xa6, 0x16, 0x81, 0xad, 0xe1, 0x0c, 0xe2,
	0x00, 0x09, 0x04, 0xa4, 0xa6, 0x16, 0x09, 0x89, 0x73, 0xb1, 0x97, 0xe4, 0x43, 0xa4, 0x98, 0xc0,
	0x52, 0x6c, 0x25, 0xf9, 0x20, 0x09, 0x29, 0x29, 0x2e, 0x16, 0x90, 0x69, 0x42, 0x42, 0x5c, 0x2c,
	0x49, 0xf9, 0x29, 0x95, 0x50, 0x8d, 0x60, 0xb6, 0x13, 0x2b, 0x17, 0x73, 0x6e, 0x71, 0x7a, 0x12,
	0x1b, 0xd8, 0x5f, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x4d, 0x8a, 0xae, 0xf4, 0x00,
	0x00, 0x00,
}
