// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/paraU/dost/dost.proto

package dost

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DostE_Status int32

const (
	DostE_unknown  DostE_Status = 0
	DostE_incoming DostE_Status = 1
	DostE_outgoing DostE_Status = 2
	DostE_accepted DostE_Status = 3
	DostE_rejected DostE_Status = 4
)

var DostE_Status_name = map[int32]string{
	0: "unknown",
	1: "incoming",
	2: "outgoing",
	3: "accepted",
	4: "rejected",
}

var DostE_Status_value = map[string]int32{
	"unknown":  0,
	"incoming": 1,
	"outgoing": 2,
	"accepted": 3,
	"rejected": 4,
}

func (x DostE_Status) String() string {
	return proto.EnumName(DostE_Status_name, int32(x))
}

func (DostE_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_234d730e0ffaa1d6, []int{0, 0}
}

type DostE struct {
	PeerId               string       `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	UserName             string       `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Status               DostE_Status `protobuf:"varint,3,opt,name=status,proto3,enum=dost.DostE_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DostE) Reset()         { *m = DostE{} }
func (m *DostE) String() string { return proto.CompactTextString(m) }
func (*DostE) ProtoMessage()    {}
func (*DostE) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d730e0ffaa1d6, []int{0}
}

func (m *DostE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DostE.Unmarshal(m, b)
}
func (m *DostE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DostE.Marshal(b, m, deterministic)
}
func (m *DostE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DostE.Merge(m, src)
}
func (m *DostE) XXX_Size() int {
	return xxx_messageInfo_DostE.Size(m)
}
func (m *DostE) XXX_DiscardUnknown() {
	xxx_messageInfo_DostE.DiscardUnknown(m)
}

var xxx_messageInfo_DostE proto.InternalMessageInfo

func (m *DostE) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *DostE) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *DostE) GetStatus() DostE_Status {
	if m != nil {
		return m.Status
	}
	return DostE_unknown
}

type DostStoreE struct {
	Dosts                []*DostE `protobuf:"bytes,1,rep,name=dosts,proto3" json:"dosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DostStoreE) Reset()         { *m = DostStoreE{} }
func (m *DostStoreE) String() string { return proto.CompactTextString(m) }
func (*DostStoreE) ProtoMessage()    {}
func (*DostStoreE) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d730e0ffaa1d6, []int{1}
}

func (m *DostStoreE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DostStoreE.Unmarshal(m, b)
}
func (m *DostStoreE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DostStoreE.Marshal(b, m, deterministic)
}
func (m *DostStoreE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DostStoreE.Merge(m, src)
}
func (m *DostStoreE) XXX_Size() int {
	return xxx_messageInfo_DostStoreE.Size(m)
}
func (m *DostStoreE) XXX_DiscardUnknown() {
	xxx_messageInfo_DostStoreE.DiscardUnknown(m)
}

var xxx_messageInfo_DostStoreE proto.InternalMessageInfo

func (m *DostStoreE) GetDosts() []*DostE {
	if m != nil {
		return m.Dosts
	}
	return nil
}

func init() {
	proto.RegisterEnum("dost.DostE_Status", DostE_Status_name, DostE_Status_value)
	proto.RegisterType((*DostE)(nil), "dost.DostE")
	proto.RegisterType((*DostStoreE)(nil), "dost.DostStoreE")
}

func init() {
	proto.RegisterFile("pkg/paraU/dost/dost.proto", fileDescriptor_234d730e0ffaa1d6)
}

var fileDescriptor_234d730e0ffaa1d6 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xbf, 0x4e, 0xc3, 0x40,
	0x0c, 0xc6, 0xb9, 0xa6, 0x4d, 0x5b, 0x07, 0xa1, 0xe8, 0x16, 0x82, 0x58, 0x42, 0xa6, 0x88, 0x21,
	0x91, 0xca, 0x2b, 0xd0, 0x81, 0x01, 0x86, 0x54, 0xcc, 0xd5, 0x91, 0x58, 0x51, 0xa8, 0x72, 0x3e,
	0xdd, 0x1f, 0xf1, 0x6a, 0x3c, 0x1e, 0xf2, 0x85, 0xa1, 0x8b, 0xe5, 0xdf, 0xf7, 0x59, 0xfe, 0x6c,
	0x78, 0x30, 0x97, 0xb1, 0x35, 0xca, 0xaa, 0xcf, 0x76, 0x20, 0xe7, 0x63, 0x69, 0x8c, 0x25, 0x4f,
	0x72, 0xcd, 0x7d, 0xf5, 0x2b, 0x60, 0xf3, 0x4a, 0xce, 0x1f, 0xe5, 0x3d, 0x6c, 0x0d, 0xa2, 0x3d,
	0x4f, 0x43, 0x21, 0x4a, 0x51, 0xef, 0xbb, 0x94, 0xf1, 0x6d, 0x90, 0x8f, 0xb0, 0x0f, 0x0e, 0xed,
	0x59, 0xab, 0x19, 0x8b, 0x55, 0xb4, 0x76, 0x2c, 0x7c, 0xa8, 0x19, 0xe5, 0x33, 0xa4, 0xce, 0x2b,
	0x1f, 0x5c, 0x91, 0x94, 0xa2, 0xbe, 0x3b, 0xc8, 0x26, 0x46, 0xc4, 0x95, 0xcd, 0x29, 0x3a, 0xdd,
	0xff, 0x44, 0xf5, 0x0e, 0xe9, 0xa2, 0xc8, 0x0c, 0xb6, 0x41, 0x5f, 0x34, 0xfd, 0xe8, 0xfc, 0x46,
	0xde, 0xc2, 0x6e, 0xd2, 0x3d, 0xcd, 0x93, 0x1e, 0x73, 0xc1, 0x44, 0xc1, 0x8f, 0xc4, 0xb4, 0x62,
	0x52, 0x7d, 0x8f, 0xc6, 0xe3, 0x90, 0x27, 0x4c, 0x16, 0xbf, 0xb1, 0x67, 0x5a, 0x57, 0x2d, 0x00,
	0xc7, 0x9c, 0x3c, 0x59, 0x3c, 0xca, 0x27, 0xd8, 0x70, 0xb2, 0x2b, 0x44, 0x99, 0xd4, 0xd9, 0x21,
	0xbb, 0xba, 0xa3, 0x5b, 0x9c, 0xaf, 0x34, 0x3e, 0xfe, 0xf2, 0x17, 0x00, 0x00, 0xff, 0xff, 0x9c,
	0xc3, 0x6e, 0x63, 0x15, 0x01, 0x00, 0x00,
}
