// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/paraU/config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoredConfig struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	EncodedKey           []byte   `protobuf:"bytes,2,opt,name=encoded_key,json=encodedKey,proto3" json:"encoded_key,omitempty"`
	PeerId               string   `protobuf:"bytes,3,opt,name=peerId,proto3" json:"peerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoredConfig) Reset()         { *m = StoredConfig{} }
func (m *StoredConfig) String() string { return proto.CompactTextString(m) }
func (*StoredConfig) ProtoMessage()    {}
func (*StoredConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4335837e3c8be070, []int{0}
}

func (m *StoredConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoredConfig.Unmarshal(m, b)
}
func (m *StoredConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoredConfig.Marshal(b, m, deterministic)
}
func (m *StoredConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredConfig.Merge(m, src)
}
func (m *StoredConfig) XXX_Size() int {
	return xxx_messageInfo_StoredConfig.Size(m)
}
func (m *StoredConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StoredConfig proto.InternalMessageInfo

func (m *StoredConfig) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *StoredConfig) GetEncodedKey() []byte {
	if m != nil {
		return m.EncodedKey
	}
	return nil
}

func (m *StoredConfig) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func init() {
	proto.RegisterType((*StoredConfig)(nil), "config.StoredConfig")
}

func init() {
	proto.RegisterFile("pkg/paraU/config/config.proto", fileDescriptor_4335837e3c8be070)
}

var fileDescriptor_4335837e3c8be070 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0xc8, 0x4e, 0xd7,
	0x2f, 0x48, 0x2c, 0x4a, 0x0c, 0xd5, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x87, 0x52, 0x7a, 0x05,
	0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x52, 0x32, 0x17, 0x4f, 0x70, 0x49, 0x7e, 0x51,
	0x6a, 0x8a, 0x33, 0x98, 0x2f, 0x24, 0xc5, 0xc5, 0x51, 0x5a, 0x9c, 0x5a, 0x94, 0x97, 0x98, 0x9b,
	0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x0b, 0xc9, 0x73, 0x71, 0xa7, 0xe6, 0x25,
	0xe7, 0xa7, 0xa4, 0xa6, 0xc4, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0x71,
	0x41, 0x85, 0xbc, 0x53, 0x2b, 0x85, 0xc4, 0xb8, 0xd8, 0x0a, 0x52, 0x53, 0x8b, 0x3c, 0x53, 0x24,
	0x98, 0xc1, 0x5a, 0xa1, 0xbc, 0x24, 0x36, 0xb0, 0x9d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x82, 0xc0, 0xb1, 0x9c, 0x94, 0x00, 0x00, 0x00,
}
